### ISSUE TITLE
cron "batch/v2alpha1" in dependencies-cron.yaml is not available

### ISSUE THREAD

**Issue by nictuku** [Financial-Times/zipkin-helm#6]
I'm getting the following error when calling:

```
$ 
helm install -f zipkin-helm.yaml https://financial-times.github.io/zipkin-helm/docs/zipkin-helm-0.4.0.tgz
Error: apiVersion "batch/v2alpha1" in zipkin-helm/templates/dependencies-cron.yaml is not available
```

**Comment by nictuku** [comment]
I guess I need to make sure the apiVersion in question is supported by my kubernetes cluster.

Should we also change that to "batch/v1beta1" which is the current API version according to these docs? https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by mclarke47** [comment]
I might be a good idea to allow people to specify their k8s version and from that infer the apiversion to use for this

**Comment by mclarke47** [comment]
Fixed in https://github.com/Financial-Times/zipkin-helm/commit/c2553dbb00c7d245cb54b051bfd3639d39fa60e9#diff-1fb4e950449dc4fc25914587f3321d6e
